AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy app codepipline'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'GitHub Info'
      Parameters:
      - GitHubOwner
      - RepositoryName
      - BranchName
    - Label:
        default: 'Codebuild'
      Parameters:
      - TestMyAppBuildSpecPath
      - ProdMyAppBuildSpecPath
#Input Parameters
Parameters:
  MyAppName:
    Default: 'robofactory'
    Description: 'My App name'
    Type: String
  TestMyAppBuildSpecPath:
    Default: 'config-files/codebuild/buildspec-test.yml'
    Description: 'Location of the buildspec file in your project'
    Type: String
  ProdMyAppBuildSpecPath:
    Default: 'config-files/codebuild/buildspec-prod.yml'
    Description: 'Location of the buildspec file in your project'
    Type: String
  RepositoryName:
    Description: GitHub repository name
    Type: String
    Default: test
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: master
  GitHubOwner:
    Type: String
  TestInfraStackName:
    Description: Test infra stack name
    Type: String
    Default: test-node-robot-catalogue-service-infra-pipeline
  ProdInfraStackName:
    Description: Prod infra stack name
    Type: String
    Default: prod-node-robot-catalogue-service-infra-pipeline       
#Build AWs resources
Resources:
  # Test Infra
  TestRobotCatalogueTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Join ['-', ['test', 'robot-catalogue', !Ref 'AWS::StackName']]
      AttributeDefinitions: 
        - 
          AttributeName: "R_NAME"
          AttributeType: "S"
        - 
          AttributeName: "R_TYPE"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "R_NAME"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes: 
        - 
          IndexName: 'type-index'
          KeySchema: 
            - 
              AttributeName: "R_TYPE"
              KeyType: "HASH"
          Projection: 
            NonKeyAttributes: 
              - "R_NAME"
              - "R_IMG_URL"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  TestMyAppECSRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Join ['/', [!Ref MyAppName, 'test', !Ref 'AWS::StackName']]
  TestAlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'ALB Security Group'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      VpcId: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:VPCID'
  TestECSEC2SGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp 
      FromPort: 3000
      ToPort: 3000
      GroupId: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:ECSEC2SG'
      SourceSecurityGroupId: !Ref TestAlbSG
  TestTaskSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'Test Task Security Group'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3000
        ToPort: 3000
        SourceSecurityGroupId: !GetAtt TestAlbSG.GroupId
      VpcId: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:VPCID'
  TestAlbTGBlue:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: '/v1/robots/healthcheck/'
      HealthCheckPort: '3000'
      HealthCheckProtocol: 'HTTP'
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      Matcher: 
        HttpCode: '200'
      Port: 3000
      Protocol: 'HTTP'
      TargetType: 'ip'
      UnhealthyThresholdCount: 4
      VpcId: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:VPCID'
  TestAlbTGGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: '/v1/robots/healthcheck/'
      HealthCheckPort: '3000'
      HealthCheckProtocol: 'HTTP'
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      Matcher: 
        HttpCode: '200'
      Port: 3000
      Protocol: 'HTTP'
      TargetType: 'ip'
      UnhealthyThresholdCount: 4
      VpcId: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:VPCID'
  TestALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Scheme: 'internet-facing'
      SecurityGroups: 
        - !GetAtt TestAlbSG.GroupId
      Subnets: 
        - Fn::ImportValue:
            !Sub '${TestInfraStackName}:PublicSubnetAId'
        - Fn::ImportValue:
            !Sub '${TestInfraStackName}:PublicSubnetBId'
      Type: 'application'
      IpAddressType: ipv4
  TestALBListner:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Order: 1
          Type: 'forward'
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref TestAlbTGBlue
                Weight: 1
      LoadBalancerArn: !Ref TestALB
      Port: 80
      Protocol: 'HTTP'
  TestMyAppTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: dynamodb
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: !GetAtt TestRobotCatalogueTable.Arn 
  TestMyAppBlueTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: 'NodeCatalogueService'
          Command: 
            - 'run'
            - 'debug'
          Environment: 
            - Name: 'MYAPP_AWS_REGION'
              Value: !Ref AWS::Region
            - Name: 'MYAPP_AWS_ENDPOINT'
              Value: !Sub 'https://dynamodb.${AWS::Region}.amazonaws.com'
            - Name: 'MYAPP_ROBOT_TABLE'
              Value: !Ref TestRobotCatalogueTable
            - Name: 'MYAPP_ROBOT_T_TYPE_INDEX'
              Value: 'type-index'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${TestMyAppECSRepo}'
          LogConfiguration: 
            LogDriver: 'awslogs'
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref TestMyAppTaskLogGroup
              awslogs-stream-prefix: 'my-app'
          PortMappings: 
            - ContainerPort: 3000
              Protocol: tcp
      Cpu: '256'
      Memory: '0.5GB'
      NetworkMode: 'awsvpc'
      RequiresCompatibilities: 
        - 'EC2'
      TaskRoleArn: !GetAtt TestMyAppTaskRole.Arn
  TestECSService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: 
        Fn::ImportValue:
          !Sub '${TestInfraStackName}:ECSClusterARN'
      DeploymentController: 
        Type: 'CODE_DEPLOY'
      DesiredCount: 2
      LaunchType: 'EC2'
      LoadBalancers: 
        - ContainerPort: 3000
          TargetGroupArn: !Ref TestAlbTGBlue
          ContainerName: 'NodeCatalogueService'
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: 'DISABLED'
          SecurityGroups: 
            - !GetAtt TestTaskSG.GroupId
          Subnets: 
            - Fn::ImportValue:
                !Sub '${TestInfraStackName}:PublicSubnetAId'
            - Fn::ImportValue:
                !Sub '${TestInfraStackName}:PublicSubnetBId'
      PlacementStrategies: 
        - Field: 'attribute:ecs.availability-zone'
          Type: 'spread'
      SchedulingStrategy: 'REPLICA'
      TaskDefinition: !Ref TestMyAppBlueTaskDefinition
  TestMyAppTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
  TestMyCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: codebuild
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
  TestMyCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
  TestMyCodeBuildLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref  TestMyCodeBuildLogGroup
      LogStreamName: "MyAppLogStream"            
  TestMyCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts: 
        OverrideArtifactName: true
        Type: 'CODEPIPELINE'
      Description: 'my app codebuild'
      Environment: 
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        PrivilegedMode: true
        Type: 'LINUX_CONTAINER'
      LogsConfig: 
        CloudWatchLogs: 
          GroupName: !Ref  TestMyCodeBuildLogGroup
          Status: 'ENABLED'
          StreamName: !Ref TestMyCodeBuildLogStream
      ServiceRole: !Ref TestMyCodeBuildRole
      Source: 
        Type: 'CODEPIPELINE'
        BuildSpec: !Ref TestMyAppBuildSpecPath
  TestCodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: 'ECS'
  # TestCodeDeployGroup:
  #   Type: AWS::CodeDeploy::DeploymentGroup
  #   Properties: 
  #     ApplicationName: !Ref TestCodeDeployApp
  #     AutoRollbackConfiguration: 
  #       Enabled: true
  #       Events: 
  #         - DEPLOYMENT_FAILURE
  #     AutoScalingGroups: 
  #       - String
  #     Deployment: 
  #       Deployment
  #     DeploymentConfigName: String
  #     DeploymentGroupName: String
  #     DeploymentStyle: 
  #       DeploymentStyle
  #     Ec2TagFilters: 
  #       - EC2TagFilter
  #     Ec2TagSet: 
  #       EC2TagSet
  #     LoadBalancerInfo: 
  #       LoadBalancerInfo
  #     OnPremisesInstanceTagFilters: 
  #       - TagFilter
  #     OnPremisesTagSet: 
  #       OnPremisesTagSet
  #     ServiceRoleArn: String
  #     TriggerConfigurations: 
  #       - TriggerConfig

  # Prod Infra
  ProdRobotCatalogueTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Join ['-', ['prod', 'robot-catalogue', !Ref 'AWS::StackName']]
      AttributeDefinitions: 
        - 
          AttributeName: "R_NAME"
          AttributeType: "S"
        - 
          AttributeName: "R_TYPE"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "R_NAME"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes: 
        - 
          IndexName: 
            Fn::Join:
              - '-'
              - - 'prod'
                - 'type-index'
          KeySchema: 
            - 
              AttributeName: "R_TYPE"
              KeyType: "HASH"
          Projection: 
            NonKeyAttributes: 
              - "R_NAME"
              - "R_IMG_URL"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  ProdMyAppECSRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Join ['/', [!Ref MyAppName, 'prod', !Ref 'AWS::StackName']]
  ProdMyAppTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: dynamodb
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: !GetAtt ProdRobotCatalogueTable.Arn 
  ProdMyAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: 'NodeCatalogueService'
          Command: 
            - 'run'
            - 'prod'
          Environment: 
            - Name: 'MYAPP_AWS_REGION'
              Value: !Ref AWS::Region
            - Name: 'MYAPP_AWS_ENDPOINT'
              Value: !Sub 'https://dynamodb.${AWS::Region}.amazonaws.com'
            - Name: 'MYAPP_ROBOT_TABLE'
              Value: !Ref ProdRobotCatalogueTable
            - Name: 'MYAPP_ROBOT_T_TYPE_INDEX'
              Value: 'type-index'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProdMyAppECSRepo}'
          LogConfiguration: 
            LogDriver: 'awslogs'
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref ProdMyAppTaskLogGroup
              awslogs-stream-prefix: 'my-app'
          PortMappings: 
            - ContainerPort: 3000
      Cpu: '256'
      Memory: '0.5GB'
      NetworkMode: 'awsvpc'
      RequiresCompatibilities: 
        - 'EC2'
      TaskRoleArn: !GetAtt ProdMyAppTaskRole.Arn
  ProdMyAppTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
  ProdMyCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: codebuild
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
  ProdMyCodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 7
  ProdMyCodeBuildLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref  ProdMyCodeBuildLogGroup
      LogStreamName: "MyAppLogStream"            
  ProdMyCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts: 
        OverrideArtifactName: true
        Type: 'CODEPIPELINE'
      Description: 'my app codebuild'
      Environment: 
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        PrivilegedMode: true
        Type: 'LINUX_CONTAINER'
      LogsConfig: 
        CloudWatchLogs: 
          GroupName: !Ref  ProdMyCodeBuildLogGroup
          Status: 'ENABLED'
          StreamName: !Ref ProdMyCodeBuildLogStream
      ServiceRole: !Ref ProdMyCodeBuildRole
      Source: 
        Type: 'CODEPIPELINE'
        BuildSpec: !Ref ProdMyAppBuildSpecPath
  # Share
  MyAppCodePipelineS3ArtifactStore:
    Type: AWS::S3::Bucket
  MyCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: codepipeline
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
  MyAppCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Location: !Ref MyAppCodePipelineS3ArtifactStore
        Type: 'S3'
      RoleArn: !GetAtt MyCodePipelineRole.Arn
      Stages: 
        - Name: 'Source'
          # https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#actions-valid-providers
          Actions:
            - Name: ApplicationSource
              ActionTypeId: 
                Category: 'Source'
                Owner: 'ThirdParty'
                Provider: 'GitHub'
                Version: '1'
              Configuration: 
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                PollForSourceChanges: false
                Branch: !Ref BranchName
                OAuthToken: '{{resolve:secretsmanager:my-app-secrets:SecretString:git-personal-access-token}}'
              InputArtifacts: []
              OutputArtifacts: 
                - Name: SourceArtifact
              RunOrder: 1
        - Name: 'TestStage'
          Actions:
            - Name: BuildContainerAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref TestMyCodeBuild
                PrimarySource: SourceArtifact
                EnvironmentVariables: !Sub |
                  [
                    {
                      "name":"REPOSITORY_URI",
                      "value":"${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${TestMyAppECSRepo}",
                      "type":"PLAINTEXT"
                    }
                  ]
              OutputArtifacts:
                - Name: TestBuildArtifact
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 2
        - Name: 'ProdStage'
          Actions:
            - Name: BuildContainerAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref ProdMyCodeBuild
                PrimarySource: SourceArtifact
                EnvironmentVariables: !Sub |
                  [
                    {
                      "name":"REPOSITORY_URI",
                      "value":"${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProdMyAppECSRepo}",
                      "type":"PLAINTEXT"
                    }
                  ]
              OutputArtifacts:
                - Name: ProdBuildArtifact
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 3
  MyAppGitHubWebHook:
    Type: AWS::CodePipeline::Webhook
    Properties: 
      Authentication: 'GITHUB_HMAC'
      AuthenticationConfiguration: 
        SecretToken: '{{resolve:secretsmanager:my-app-secrets:SecretString:git-personal-access-token}}'
      Filters: 
        - JsonPath: $.ref
          MatchEquals: 'refs/heads/{Branch}'
      RegisterWithThirdParty: true
      TargetAction: 'ApplicationSource'
      TargetPipeline: !Ref MyAppCodePipeline
      TargetPipelineVersion: !GetAtt MyAppCodePipeline.Version

Outputs:
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'